/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ChainLanceEscrow {
  export type EscrowTransactionStruct = {
    milestoneId: string;
    client: AddressLike;
    freelancer: AddressLike;
    amount: BigNumberish;
    isReleased: boolean;
    isRefunded: boolean;
    createdAt: BigNumberish;
  };

  export type EscrowTransactionStructOutput = [
    milestoneId: string,
    client: string,
    freelancer: string,
    amount: bigint,
    isReleased: boolean,
    isRefunded: boolean,
    createdAt: bigint
  ] & {
    milestoneId: string;
    client: string;
    freelancer: string;
    amount: bigint;
    isReleased: boolean;
    isRefunded: boolean;
    createdAt: bigint;
  };
}

export interface ChainLanceEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createEscrow"
      | "escrows"
      | "getEscrow"
      | "refund"
      | "release"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCreated"
      | "EscrowRefunded"
      | "EscrowReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [string]): string;
  encodeFunctionData(functionFragment: "getEscrow", values: [string]): string;
  encodeFunctionData(functionFragment: "refund", values: [string]): string;
  encodeFunctionData(functionFragment: "release", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    milestoneId: string,
    client: AddressLike,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    client: string,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    client: string;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    milestoneId: string,
    client: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    client: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    client: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    milestoneId: string,
    freelancer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: string,
    freelancer: string,
    amount: bigint
  ];
  export interface OutputObject {
    milestoneId: string;
    freelancer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainLanceEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ChainLanceEscrow;
  waitForDeployment(): Promise<this>;

  interface: ChainLanceEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createEscrow: TypedContractMethod<
    [_milestoneId: string, _freelancer: AddressLike],
    [void],
    "payable"
  >;

  escrows: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean, boolean, bigint] & {
        milestoneId: string;
        client: string;
        freelancer: string;
        amount: bigint;
        isReleased: boolean;
        isRefunded: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [_milestoneId: string],
    [ChainLanceEscrow.EscrowTransactionStructOutput],
    "view"
  >;

  refund: TypedContractMethod<[_milestoneId: string], [void], "nonpayable">;

  release: TypedContractMethod<[_milestoneId: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [_milestoneId: string, _freelancer: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean, boolean, bigint] & {
        milestoneId: string;
        client: string;
        freelancer: string;
        amount: bigint;
        isReleased: boolean;
        isRefunded: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [_milestoneId: string],
    [ChainLanceEscrow.EscrowTransactionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[_milestoneId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[_milestoneId: string], [void], "nonpayable">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(string,address,address,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRefunded(string,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(string,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
  };
}
